// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "kelarin/internal/types"
)

// Notification is an autogenerated mock type for the Notification type
type Notification struct {
	mock.Mock
}

// SaveToken provides a mock function with given fields: ctx, req
func (_m *Notification) SaveToken(ctx context.Context, req types.NotificationSaveTokenReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NotificationSaveTokenReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendPush provides a mock function with given fields: ctx, req
func (_m *Notification) SendPush(ctx context.Context, req types.NotificationSendReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendPush")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NotificationSendReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotification creates a new instance of Notification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notification {
	mock := &Notification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
