// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Util is an autogenerated mock type for the Util type
type Util struct {
	mock.Mock
}

// NormalizeTimeOnlyTz provides a mock function with given fields: timeOnly
func (_m *Util) NormalizeTimeOnlyTz(timeOnly time.Time) time.Time {
	ret := _m.Called(timeOnly)

	if len(ret) == 0 {
		panic("no return value specified for NormalizeTimeOnlyTz")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(time.Time) time.Time); ok {
		r0 = rf(timeOnly)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// ParseUserTimeZone provides a mock function with given fields: tz
func (_m *Util) ParseUserTimeZone(tz string) (*time.Location, error) {
	ret := _m.Called(tz)

	if len(ret) == 0 {
		panic("no return value specified for ParseUserTimeZone")
	}

	var r0 *time.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*time.Location, error)); ok {
		return rf(tz)
	}
	if rf, ok := ret.Get(0).(func(string) *time.Location); ok {
		r0 = rf(tz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tz)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUtil creates a new instance of Util. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *Util {
	mock := &Util{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
