[Unit]
Description=Elasticsearch
Documentation=https://www.elastic.co/guide/en/elasticsearch/reference/8.17/index.html
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=elasticsearch
Group=elasticsearch
ExecStart=/opt/elasticsearch-8.17.0/bin/elasticsearch
LimitNOFILE=65535
LimitNPROC=4096
TimeoutStopSec=0
Restart=always
WorkingDirectory=/opt/elasticsearch-8.17.0
Environment=ES_PATH_CONF=/opt/elasticsearch-8.17.0/config

[Install]
WantedBy=multi-user.target