// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	dbUtil "kelarin/internal/utils/dbutil"

	mock "github.com/stretchr/testify/mock"

	types "kelarin/internal/types"

	uuid "github.com/google/uuid"
)

// ConsumerNotification is an autogenerated mock type for the ConsumerNotification type
type ConsumerNotification struct {
	mock.Mock
}

// CreateTx provides a mock function with given fields: ctx, tx, req
func (_m *ConsumerNotification) CreateTx(ctx context.Context, tx dbUtil.Tx, req types.ConsumerNotification) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dbUtil.Tx, types.ConsumerNotification) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByUserID provides a mock function with given fields: ctx, userID
func (_m *ConsumerNotification) FindAllByUserID(ctx context.Context, userID uuid.UUID) ([]types.ConsumerNotificationWithServiceProviderAndPayment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []types.ConsumerNotificationWithServiceProviderAndPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]types.ConsumerNotificationWithServiceProviderAndPayment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []types.ConsumerNotificationWithServiceProviderAndPayment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ConsumerNotificationWithServiceProviderAndPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConsumerNotification creates a new instance of ConsumerNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerNotification {
	mock := &ConsumerNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
