// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	dbUtil "kelarin/internal/utils/dbutil"

	mock "github.com/stretchr/testify/mock"

	types "kelarin/internal/types"

	uuid "github.com/google/uuid"
)

// ServiceProviderNotification is an autogenerated mock type for the ServiceProviderNotification type
type ServiceProviderNotification struct {
	mock.Mock
}

// CreateTx provides a mock function with given fields: ctx, tx, req
func (_m *ServiceProviderNotification) CreateTx(ctx context.Context, tx dbUtil.Tx, req types.ServiceProviderNotification) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dbUtil.Tx, types.ServiceProviderNotification) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByServiceProviderID provides a mock function with given fields: ctx, serviceProviderID
func (_m *ServiceProviderNotification) FindAllByServiceProviderID(ctx context.Context, serviceProviderID uuid.UUID) ([]types.ServiceProviderNotificationWithUser, error) {
	ret := _m.Called(ctx, serviceProviderID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByServiceProviderID")
	}

	var r0 []types.ServiceProviderNotificationWithUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]types.ServiceProviderNotificationWithUser, error)); ok {
		return rf(ctx, serviceProviderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []types.ServiceProviderNotificationWithUser); ok {
		r0 = rf(ctx, serviceProviderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ServiceProviderNotificationWithUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, serviceProviderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceProviderNotification creates a new instance of ServiceProviderNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProviderNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProviderNotification {
	mock := &ServiceProviderNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
