services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 10s
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-external-labels: container_name={{.Name}},svc=postgres

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6378:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 5
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-external-labels: container_name={{.Name}},svc=redis

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - 3000:${API_PORT}
    volumes:
      - ../config:/app/config
      - ../database:/app/database
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    restart: no
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-external-labels: container_name={{.Name}},svc=svc-backend

  cronjob:
    container_name: cronjob
    build:
      context: ..
      dockerfile: docker/cronjob.Dockerfile
    volumes:
      - ../config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_healthy
    restart: no
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-external-labels: container_name={{.Name}},svc=cronjob

volumes:
  es_data:
    driver: local
  pg_data:
    driver: local
  redis_data:
    driver: local
  loki_data:
    driver: local
