services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6378:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3000:${API_PORT}
    volumes:
      - ../config:/app/config
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      loki:
        condition: service_started
    restart: no
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

volumes:
  es_data:
    driver: local
  pg_data:
    driver: local
  redis_data:
    driver: local
  loki_data:
    driver: local
