environment: "development"
pretty_log: false

server:
  host: "127.0.0.1"
  port: 3000
  cors:
    allowed_origins:
      - "http://localhost:5173"

database:
  connection_string: "postgres://postgres:root@localhost:5432/kelarin?sslmode=disable"
  max_idle_cons: 5
  max_open_cons: 20

redis:
  connection_string: "redis://localhost:6379"

jwt:
  secret_key: "secret"
  refresh_token_secret_key: "secret"
  issuer: "localhost"
  expiration: 24h
  refresh_token_expiration: 720h

oauth:
  google:
    client_id: "client_id"