// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"firebase.google.com/go/messaging"
	"github.com/alexliesenfeld/opencage"
	"github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/elastic/go-elasticsearch/v8"
	"github.com/gorilla/websocket"
	"github.com/hibiken/asynq"
	"github.com/jmoiron/sqlx"
	"github.com/midtrans/midtrans-go/snap"
	"github.com/redis/go-redis/v9"
	"kelarin/internal/config"
	"kelarin/internal/handler"
	"kelarin/internal/middleware"
	"kelarin/internal/provider"
	"kelarin/internal/queue/task"
	"kelarin/internal/repository"
	"kelarin/internal/service"
	"kelarin/internal/types"
	"kelarin/internal/utils/dbutil"
)

// Injectors from wire.go:

func newServer(db *sqlx.DB, esDB *elasticsearch.TypedClient, config2 *config.Config, redis2 *redis.Client, s3UploadManager *manager.Uploader, queueClient *asynq.Client, s3Client *s3.Client, s3PresignClient *s3.PresignClient, opencageClient *opencage.Client, firebaseMessagingClient *messaging.Client, midtransSnapClient *snap.Client, wsUpgrader *websocket.Upgrader, wsHub *types.WsHub, mainDBTx dbUtil.SqlxTx) (*provider.Server, error) {
	user := repository.NewUser(db)
	serviceUser := service.NewUser(user)
	handlerUser := handler.NewUser(serviceUser)
	session := repository.NewSession(redis2)
	pendingRegistration := repository.NewPendingRegistration(redis2)
	auth := service.NewAuth(config2, mainDBTx, session, user, pendingRegistration)
	handlerAuth := handler.NewAuth(auth)
	file := repository.NewFile(redis2)
	tempFile := task.NewTempFile(queueClient)
	serviceFile := service.NewFile(redis2, config2, file, tempFile, s3PresignClient, s3UploadManager, s3Client)
	handlerFile := handler.NewFile(serviceFile)
	serviceProvider := repository.NewServiceProvider(db)
	province := repository.NewProvince(db)
	city := repository.NewCity(db)
	serviceProviderArea := repository.NewServiceProviderArea(db)
	geocoding := service.NewGeocoding(opencageClient)
	serviceServiceProvider := service.NewServiceProvider(db, serviceProvider, user, province, city, serviceProviderArea, pendingRegistration, serviceFile, geocoding)
	middlewareAuth := middleware.NewAuth(config2, session)
	handlerServiceProvider := handler.NewServiceProvider(serviceServiceProvider, middlewareAuth)
	serviceIndex := repository.NewServiceIndex(esDB)
	repositoryService := repository.NewService(db)
	serviceCategory := repository.NewServiceCategory(db)
	serviceServiceCategory := repository.NewServiceServiceCategory(db)
	serviceService := service.NewService(mainDBTx, serviceIndex, serviceProvider, repositoryService, serviceCategory, serviceServiceCategory, serviceProviderArea, serviceFile)
	order := repository.NewOrder(db)
	serviceFeedback := repository.NewServiceFeedback(db)
	consumerService := service.NewConsumerService(mainDBTx, serviceIndex, repositoryService, serviceProviderArea, serviceProvider, serviceFile, order, serviceFeedback)
	handlerService := handler.NewService(serviceService, consumerService, middlewareAuth)
	serviceProvince := service.NewProvince(province)
	handlerProvince := handler.NewProvince(serviceProvince)
	serviceCity := service.NewCity(city)
	handlerCity := handler.NewCity(serviceCity)
	serviceCategory2 := service.NewServiceCategory(serviceCategory)
	handlerServiceCategory := handler.NewServiceCategory(serviceCategory2)
	userAddress := repository.NewUserAddress(db)
	serviceUserAddress := service.NewUserAddress(userAddress, geocoding)
	handlerUserAddress := handler.NewUserAddress(serviceUserAddress, middlewareAuth)
	offer := repository.NewOffer(db)
	offerNegotiation := repository.NewOfferNegotiation(db)
	serviceProviderNotification := repository.NewServiceProviderNotification(db)
	fcmToken := repository.NewFCMToken(redis2)
	notification := service.NewNotification(db, firebaseMessagingClient, fcmToken)
	consumerNotification := repository.NewConsumerNotification(db)
	chatRoom := repository.NewChatRoom(db)
	chatRoomUser := repository.NewChatRoomUser(db)
	chatMessage := repository.NewChatMessage(db)
	util := service.NewUtil()
	chat := service.NewChat(mainDBTx, repositoryService, user, chatRoom, chatRoomUser, chatMessage, wsHub, offer, serviceProvider, serviceFile, order, util)
	serviceOffer := service.NewOffer(mainDBTx, offer, userAddress, repositoryService, serviceFile, serviceProvider, offerNegotiation, serviceProviderNotification, fcmToken, notification, user, consumerNotification, chat, order, util)
	handlerOffer := handler.NewOffer(serviceOffer, middlewareAuth)
	serviceOfferNegotiation := service.NewOfferNegotiation(mainDBTx, serviceProvider, offerNegotiation, offer, repositoryService, notification, fcmToken, serviceFile, consumerNotification, serviceProviderNotification, user)
	handlerOfferNegotiation := handler.NewOfferNegotiation(middlewareAuth, serviceOfferNegotiation)
	serviceConsumerNotification := service.NewConsumerNotification(mainDBTx, user, consumerNotification, util, serviceFile)
	serviceServiceProviderNotification := service.NewServiceProviderNotification(serviceProvider, serviceProviderNotification, util)
	handlerNotification := handler.NewNotification(middlewareAuth, notification, serviceConsumerNotification, serviceServiceProviderNotification)
	payment := repository.NewPayment(db)
	paymentMethod := repository.NewPaymentMethod(db)
	midtrans := service.NewMidtrans(midtransSnapClient)
	servicePayment := service.NewPayment(config2, mainDBTx, payment, paymentMethod, order, midtrans, notification, fcmToken, consumerNotification, serviceProviderNotification)
	handlerPayment := handler.NewPayment(servicePayment, middlewareAuth)
	serviceOrder := service.NewOrder(mainDBTx, order, serviceFile, util, serviceOffer, payment, paymentMethod, config2, serviceProvider, consumerNotification, serviceProviderNotification, fcmToken, notification, repositoryService, serviceFeedback)
	handlerOrder := handler.NewOrder(serviceOrder, middlewareAuth)
	servicePaymentMethod := service.NewPaymentMethod(paymentMethod)
	handlerPaymentMethod := handler.NewPaymentMethod(servicePaymentMethod)
	report := service.NewReport(serviceProvider, offer, order, util)
	handlerReport := handler.NewReport(report, middlewareAuth)
	handlerChat := handler.NewChat(wsUpgrader, chat, wsHub, middlewareAuth)
	server := provider.NewServer(handlerUser, handlerAuth, handlerFile, handlerServiceProvider, handlerService, handlerProvince, handlerCity, handlerServiceCategory, handlerUserAddress, handlerOffer, handlerOfferNegotiation, handlerNotification, handlerPayment, handlerOrder, handlerPaymentMethod, handlerReport, handlerChat, middlewareAuth)
	return server, nil
}
